### ISSUE TITLE
Update ORCiD Endpoints

### ISSUE THREAD

**Issue by thostetler** [adsabs/orcid-service#13]
I need the `orcid-works` endpoint updated.

- **Adding New Work(s)**
  - Single Record
    - Method: `POST`
    - Request: `orcid-works/` -> `work/`
    - Response: (Status Only) 201 CREATED
  - Bulk
    - Method: `POST`
    - Request: `orcid-works/` -> `works/`
    - Response: (Bulk JSON) 200 OK

- **Reading Work(s)**
  - Single Record
    - Method: `GET`
    - Request: `orcid-works/[PUT-CODE]` -> `work/[PUT-CODE]`
    - Response: (Single Record JSON) 200 OK
  - Bulk
    - Method: `GET`
    - Request: `orcid-works/` -> `works/`
    - Request: `orcid-works/[PUT-CODE],...` -> `works/[PUT-CODE],...`
    - Response: (Bulk JSON) 200 OK

- **Updating Work**
  - Single Record
    - Method: `PUT`
    - Request: `orcid-works/[PUT-CODE]` -> `work/[PUT-CODE]`
    - Response: (Single Record JSON) 200 OK

- **Delete Work**
  - Single Record
    - Method: `DELETE`
    - Request: `orcid-works/[PUT-CODE]` -> `work/[PUT-CODE]`
    - Response: (Status Only) 204 NO CONTENT

**Comment by thostetler** [comment]
Really, we could probably just _always_ do a bulk add/read.  I don't see a reason to worry about the single ADD/READ case.  

It simplifies things a bit too, then everything can be `orcid-works`

**Comment by kelockhart** [comment]
PR #14
